//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Klub.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_KLUB_FORM                   101
#define IDP_FAILED_OPEN_DATABASE        103
#define IDR_MAINFRAME                   128
#define IDR_KlubTYPE                    130
#define IDD_DIALOG_CLANOVI              311
#define IDD_DIALOG_CLANARINE            312
#define IDD_DIALOG_PRIKAZ_CLANOVA       316
#define IDD_DIALOG_PRIKAZ_CLANARINA     318
#define IDD_DIALOG_NATJECANJA           320
#define IDD_DIALOG_PRIKAZ_NATJECANJA    323
#define IDC_BUTTON1                     1000
#define IDC_BTN_CLANOVI                 1000
#define IDC_BTN_PRIKAZI_CLANOVE         1000
#define IDC_BTN_PRIKAZI_UPLATE          1000
#define IDC_BTN_ISPISI_PRIKAZ           1000
#define IDC_BTN_POCETNA3                1000
#define IDC_BUTTON2                     1001
#define IDC_BTN_CLANARINE               1001
#define IDC_RD_NOVI_CLAN                1001
#define IDC_BTN_IDI_NA_CLANOVE          1001
#define IDC_IDI_NA_CLANOVE1             1001
#define IDC_BTN_POCETNA2                1001
#define IDC_BTN_ZATVORI3                1001
#define IDC_BTN_POCETNA4                1001
#define IDC_BTN_POCETNA5                1001
#define IDC_BTN_CLANOVI1                1001
#define IDC_BUTTON3                     1002
#define IDC_BTN_NATJECANJA              1002
#define IDC_RD_PROMJENA_CLANOVI         1002
#define IDC_BTN_SPREMI_REZ              1002
#define IDC_BTN_IDI_NA_CLANARINE        1002
#define IDC_BTN_ZATVORI2                1002
#define IDC_BTN_ZATVORI5                1002
#define IDC_BTN_CLANARINE4              1002
#define IDC_BUTTON4                     1003
#define IDC_BTN_ISPIS                   1003
#define IDC_EDIT_IME_CLANA              1003
#define IDC_BTN_ODUSTANI_REZ            1003
#define IDC_BTN_ZATVORI_APLIKACIJU      1003
#define IDC_BTN_POCETNA                 1003
#define IDC_BTN_CLANOVIx                1003
#define IDC_BTN_CLANOVI5                1003
#define IDC_COMBO_CLANOVI_IMENA         1004
#define IDC_COMBO_SPOL                  1005
#define IDC_DAT_ROD                     1006
#define IDC_COMBO_AKT                   1007
#define IDC_EDIT_TEL                    1008
#define IDC_EDIT_ADRESA                 1009
#define IDC_EDIT_MAIL                   1010
#define IDC_RD_AKTIVNI                  1012
#define IDC_RD_NEAKTIVNI                1013
#define IDC_RD_SVI                      1014
#define IDC_STATIC_IME                  1015
#define IDC_BTN_SPREMI                  1016
#define IDC_BTN_ODUSTANI                1017
#define IDC_EDIT_ID_CLANA               1019
#define IDC_EDIT_SVRHA_UPLATE           1019
#define IDC_LIST_CLANOVI                1033
#define IDC_RD_UNOS_UPLATE              1034
#define IDC_RD_PROMJENA_CLANARINE       1035
#define IDC_COMBO_UPLATITELJ            1036
#define IDC_DAT_UPLATE                  1037
#define IDC_COMBO_IZNOS_UPLATE          1038
#define IDC_COMBO_LISTA_UPLATA          1039
#define IDC_RD_CLAN                     1054
#define IDC_RD_KLUB                     1055
#define IDC_DAT_OD                      1056
#define IDC_DAT_DO                      1057
#define IDC_STATIC_UPLATITELJ           1058
#define IDC_STATIC_LISTA_UPLATA         1059
#define IDC_COMBO_ID_CLANARINE          1060
#define IDC_RADIO1                      1064
#define IDC_RD_PROMJENA_UNOSA           1066
#define IDC_RD_UNOS_NATJECANJA          1067
#define IDC_EDIT_NAZIV_NATJECANJA       1068
#define IDC_COMBO_LISTA_NATJECANJA      1069
#define IDC_EDIT_KOEFICIJENT            1070
#define IDC_DAT_ODRZAVANJA              1071
#define IDC_COMBO_NATJECANJE_REZ        1072
#define IDC_COMBO_NATJECATELJ           1073
#define IDC_LIST1                       1074
#define IDC_LIST_REZULTAT               1074
#define IDC_LISTA                       1074
#define IDC_EDIT_KATEGORIJA             1075
#define IDC_BTN_SPREMI_NATJ             1076
#define IDC_BTN_ODUSTANI_NATJ           1077
#define IDC_RD_UNOS_REZULTATA           1078
#define IDC_RD_PROMJENA_REZULTATA       1079
#define IDC_RD_NATJECATELJ              1080
#define IDC_RD_NATJECANJE               1082
#define IDC_COMBO_NATJECATELJ_PRIKAZ    1083
#define IDC_COMBO_NATJECANJE_PRIKAZ     1084
#define IDC_DATE_OD                     1085
#define IDC_DATE_DO                     1086
#define IDC_BUTTON5                     1087
#define IDC_BTN_PRIKAZI                 1087
#define IDC_BTN_POCETNA1                1087
#define IDC_BTN_NATJECANJAx             1087
#define IDC_RADIO8                      1088
#define IDC_RD_NATJECANJA               1088
#define IDC_RADIO9                      1089
#define IDC_RADIO_REZULTATI             1089
#define IDC_RADIO10                     1090
#define IDC_RD_PRIKAZ                   1092
#define IDC_GRPUA_NATJECANJA            1093
#define IDC_GRUPA_NATJECANJA            1093
#define IDC_RD_PROMJENA_REZ_ZA_NATJECANJE 1097
#define IDC_RD_PROMJENA_UNOSA_REZ_ZA_NATJECATELJA 1098
#define IDC_COMBO_REZULRAT              1099
#define IDC_COMBO_REZULTAT              1099
#define IDC_EDIT_POM                    1100
#define IDC_LIST_PODACI                 1101
#define IDC_EDIT1                       1102
#define IDC_EDIT_POM2                   1102
#define IDC_COMBO                       1108
#define IDC_RD_SVE_UPLATE               1114
#define IDC_RD_RAZDOBLJE                1115
#define IDC_COMBO_NATJECANJE            1119
#define IDC_STATIC_POM                  1122
#define IDC_COMBO_POM                   1123
#define IDC_BTN_IDI_NA_NATJECANJA       1124
#define IDC_BTN_IDI_NA_CLANARINE1       1126
#define IDC_BTN_IDI_NA_NATJECANJA1      1127
#define IDC_BTN_ZATVORI_APLIKACIJU1     1128
#define IDC_BTN_ZATVORI1                1129
#define IDC_CLANARINE1                  1130
#define IDC_BTN_NATJECANJA1             1131
#define IDC_BTN_CLANOVI3                1132
#define IDC_BTN_CLANARINE3              1133
#define IDC_BTN_NATJECANJA4             1134
#define IDC_BTN_CLANARINE5              1135
#define IDC_COMBO1                      1136
#define ID_BUTTON32771                  32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        331
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1137
#define _APS_NEXT_SYMED_VALUE           324
#endif
#endif
